stages:
  - build
  - test
  - deploy

language: node_js

node_js:
  - 12

cache:
  directories:
    - $(npm config get prefix)/lib/node_modules

before_install:
  - npm install -g npm@7.14.0
  - npm install -g @fleekhq/fleek-cli
  - npm install -g truffle

jobs:
  include:
    - stage: build
      script:
        - truffle compile
        - cd client
        - npm install
        - npm run build
    - stage: test
      name: "Test Smart Contracts"
      script:
        - truffle test
    - name: "Test Front-end"
      script:
        - truffle compile
        - cd client
        - npm install
        - npm test
    - stage: deploy
      script:
        - fleek site:deploy









